# GridGain license — single source of truth for the Gradle build.
#
# The build reads this file and passes the resolved location to every embedded GridGain component
# (FxcExchange, FxcBroker, FxcPub) when launched through Gradle's `run` and `test` targets, as the
# -Dgridgain.license.url system property. Change the license location here in exactly one place.
#
# The value is either a path (resolved relative to this repo root) or a URL (file:, http:, ...).
# The referenced license file itself is gitignored; keep it out of version control.
gridgain.license.file=gridgain-license.xml
